version: "3.8"

services:
  diary_service:
    container_name: diary_diary_service
    build: diary
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - diary/src
    depends_on:
      - diary_db

  diary_db:
    container_name: diary_diary_db
    image: postgres:15
    hostname: ${POSTGRES__HOST}
    ports:
      - "${POSTGRES__PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DBNAME}
