version: "3"

services:
  web:
    build: ./fastapi
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    hostname: ${POSTGRES__HOST}
    ports:
      - "${POSTGRES__PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DBNAME}
